DAND-7- Update Amplitude and Segment Analytics.
segment-integrations/analytics-ios-integration-amplitude pull request #70
Opened 2019-11-05 17:19 UTC by OllaAshour

**What does this PR do?**

Update Amplitude and Segment Analytics SDK to latest version and also other dependencies.

- Analytics (3.7.0)
- Expecta (1.0.6)
- OCHamcrest (7.1.2)
- OCMockito (5.1.2)
- Segment-Amplitude (2.0.1-beta)
- Specta (1.0.7)

**Associated JIRA Tickets:**
https://segmentcontractors.atlassian.net/browse/DAND-7

2019-11-13 19:34 UTC, briemcnally requested changes
Left one comment, otherwise looks amazing! Thanks for the great work!

2019-11-13 19:34 UTC, briemcnally commented on Segment-Amplitude.podspec
>  end
@OllaAshour can we actually add the specific upgraded target versions back here.  The` Example/Podfile.lock` is just keeping track of what's there, but if a customer does a pod install, that lock isn't going to be looked at and will be overwritten by the latest version which will be pulled by the `.podspec`  unless we indicate a target version for the dependency. The path of just taking the "latest" (not specifying version) is leaving us open to incompatibilities when a partner makes a backwards incompatible change to their SDK.

2019-11-18 23:07 UTC, briemcnally commented on Segment-Amplitude.podspec
> +  s.dependency 'Analytics', '~> 3.6' # support for iOS 7 +
Can we actually change this back to the dependencies we are trying to bump to: ie: Analytics (3.7.0) and Amplitude-iOS (4.8.2)?

2021-04-15 20:46 UTC, migs647 commented
Since been updated

2021-04-15 20:46 UTC, closed without merging